name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22.x"

      - name: Install yarn
        run: npm install --global yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Publish release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn electron-forge publish --arch arm64,x64
